# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: LogLink documentation

repo_url: https://github.com/hankhank10/loglink-server

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - navigation.footer

plugins:
    - mkdocs-video:
        css_style:
            width: 400px
            height: 400px

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
    - 'index.md'
    - 'security-notice.md'
    - 'Quickstart Guides':
        - 'telegram-quickstart.md'
        - 'setup-plugin.md'
        - 'image-upload.md'
    - 'Self Deployment Guide':
        - 'Tech stack intro': 'technologies-used.md'
        - 'self-deploy.md'
    - 'Development':
      - 'How to contribute': 'technologies-used.md'
      - 'Development roadmap': 'roadmap.md'
      - 'Changelogs': 'changelog.md'